### ISSUE TITLE
Implementation Missing

### ISSUE THREAD

**Issue by hermannsblum** [SonginCV/GMPHD_MAF#1]
HI! It looks like you started this repository to upload your implementation, but never finished it. Do you still plan on publishing the implementation?

**Comment by SonginCV** [comment]
Hello, now I have been preparing a journal submission with more experiments.

Yes I have a plan to publish the implementation.
I think that implementation codes will be uploaded in a month.
(after submitting a journal draft)

Thank you for having a interest in my work.

**Comment by hermannsblum** [comment]
wonderful :)
Good luck for the journal submission then! I was simply searching for a precise and fast tracking solution for some robotic experiments. I will start with basic opencv and hopefully upgrade to your method in a month :)

**Comment by hellodhd** [comment]
hello，sorry to ask， Do you still plan on publishing the implementation?  ThX！

**Comment by SonginCV** [comment]
Dear @hermannsblum and @hellodhd,

Finally I have committed the first full source codes.
Thank you for being interested in my work.
Details of our method are described in README.md

Regard,
from Young-min Song
